version: "3"
services:
    app:
        build:
          args:
            user: sammy
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: apipos
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www/
        networks:
          - apiposnetwork

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
          - "3306:3306"
        volumes:
          - dbdata:/var/lib/mysql/
        environment:
          MYSQL_DATABASE: laravel 
          MYSQL_ROOT_PASSWORD: password
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        networks:
          - apiposnetwork
          
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - 443:443
        volumes:
            - ./:/var/www/
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - apiposnetwork

networks:
    apiposnetwork:
        driver: bridge

volumes:
  dbdata:
    driver: local